# Generated by Django 4.0 on 2022-02-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='html',
            field=models.TextField(max_length=4096, verbose_name='Содержание страницы '),
        ),
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(help_text='Оставьте только одно единственное активный объект для отображения желаемого контента', verbose_name='Активность'),
        ),
    ]
