# Generated by Django 4.0 on 2022-02-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_html_alter_about_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='html',
            field=models.TextField(max_length=8192, verbose_name='Содержание страницы '),
        ),
    ]
