# Generated by Django 4.0 on 2022-02-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_about_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Участника', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='img',
            field=models.ImageField(default='contact/default.jpg', help_text='Фото участника', upload_to='contact/', verbose_name='Фото'),
        ),
    ]
