# Generated by Django 4.0 on 2022-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_options_alter_contact_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название партнёра', max_length=32, verbose_name='Название')),
                ('img', models.ImageField(default='partners/default.jpg', help_text='Фото партнёра', upload_to='partners/', verbose_name='Фото')),
                ('url', models.URLField(help_text='Описание участника', max_length=256, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Партнёра',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
